[package]
name = "smalloclog"
version = "0.3.0"
edition = "2024"

[dependencies]
atomic-dbg = "0.1.11"
bytesize = "2.0.1"
rand = "0.9.0"
rustc-hash = "2.1.1"
smalloc = { version = "0.2", path = "/Users/donaldturnworth/playground/smalloc" }
thousands = "0.2.0"
